# .streamlit/secrets.toml

[firebase]
apiKey            = "AIzaSyBLV0E230b20k-1qDREXF5Uel4Zl1jwpFE"
authDomain        = "suvecopass.firebaseapp.com"
projectId         = "suvecopass"
storageBucket     = "suvecopass.firebasestorage.app"
messagingSenderId = "294427619327"
appId             = "1:294427619327:web:5f7ca1178814341bb001ca"